SUPABASE_URL = "https://zxysqsirkbrfsraxlopq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4eXNxc2lya2JyZnNyYXhsb3BxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTgxOTE3NywiZXhwIjoyMDY1Mzk1MTc3fQ.z3KWuJFjT-7w0dijsG57Z3HzNdJoSx0QRZLTJ6SUSks"
SUPABASE_TABLE = "users"
